// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwwrgmdsugdroriydkpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3d3JnbWRzdWdkcm9yaXlka3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDI4NTMsImV4cCI6MjA3MTk3ODg1M30.4fVvO_XSg3DJBFAKV51IfbldOmltl1gcyNdnNqlYkPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});